### ISSUE TITLE
Teaching & Training Community  Onboarding

### ISSUE THREAD

**Issue by emmairwin** [mozilla/community-teaching-training#2]
Design light-weight community onboarding  workflow 
1.  Review and improve content / invitation to join the community channels on this portal page   http://mozilla.github.io/community-teaching-training/   .
2. Create README.md and CONTRIBUTING.md  link to mozillians group and main page. keep super simple for now.

**Comment by anistuhin** [comment]
Wow, didn't know of this Repo :P Would like to support for any kinds of developer support. With other issues will be occasional but keep updates =D Btw, what about touching the page a bit to make it maybe a little nicer with some colors and aligning, may be a common footer like we use on all Mozilla site?? :P

**Comment by emmairwin** [comment]
Hey @anistuhin thanks so much, actually there are some coding tasks outstanding over here:  https://github.com/mozilla/participation-curriculum/issues  if your interested.

**Comment by emmairwin** [comment]
Closing this issue for now, while we work on vision statement .
